### PR TITLE
Suggest to use RFC3339 for -f and -t options

### PR DESCRIPTION
**Pull request by EugeneChung**
- About RFC3339 : https://medium.com/easyread/understanding-about-rfc-3339-for-datetime-formatting-in-software-engineering-940aa5d5f68a
- RFC3339 supports `2019-07-31T17:03:00.000Z` as it is.
- Time-zone can be specified like this `2019-07-31T20:03:00.000+03:00`.

### CODE REVIEW

**Comment by barasher** [comment]
Great idea, thanks for the PR !

**Comment by barasher** [comment]
@EugeneChung, you've submitted this PR 12 minutes after the v1.3 release yesterday (that contained your previous PR #16). Do you have anything else in mind or do I release a new version right now ? :)

**Comment by EugeneChung** [comment]
That's okay. I just wanted to share it. I'm using the forked one.

**Comment by EugeneChung** [comment]
@barasher There's one more thing I have in mind. I'm going to address it as an issue first.

**Pull request merged**
